# Generated by Django 3.0.6 on 2020-06-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='req_group', to='groups.Group'),
        ),
    ]
